### ISSUE TITLE
Default URL for current_data.tar.gz is 404

### ISSUE THREAD

**Issue by nicholst** [neurosynth/neurosynth#102]
In [`neurosynth/base/dataset.py#L38`](https://github.com/neurosynth/neurosynth/blob/master/neurosynth/base/dataset.py#L38) the default download dataset is listed as 

```
https://github.com/neurosynth/neurosynth-data/blob/master/current_data.tar.gz?raw=true
```

but it isn't in the current version of the `neurosynth-data` repo.  In fact, in there is currently no `.tar.gz` file.

Possibly the problem isn't just that this file is missing, but that the [neurosynth/README.md?plain=1#L55](https://github.com/neurosynth/neurosynth/blob/master/README.md?plain=1#L55) line
```
	ns.dataset.download(path='.', unpack=True)
```
throws an error 
```
>>> ns.dataset.download(path='.', unpack=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/nichols/git/neurosynth/neurosynth/base/dataset.py", line 47, in download
    u = urlopen(url)
  File "/anaconda3/envs/py3/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/anaconda3/envs/py3/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/anaconda3/envs/py3/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/anaconda3/envs/py3/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/anaconda3/envs/py3/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/anaconda3/envs/py3/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

Maybe it needs to be changed to `https://github.com/neurosynth/neurosynth-data/blob/master/data-neurosynth_version-7_coordinates.tsv.gz` (except this is `.tsv.gz` instead of `.tar.gz`)

**Comment by sorenjmadsen** [comment]
Looks like the repo was updated and removed the file.

Here's a link to the most recent commit that included the file. You'll have to download the file manually, but it's better than nothing. 

https://github.com/neurosynth/neurosynth-data/blob/e8f27c4a9a44dbfbc0750366166ad2ba34ac72d6/current_data.tar.gz

EDIT: Seems like the new thing to use is NiMARE. 

https://github.com/neurosynth/neurosynth/issues/105#issuecomment-1839357491
